### ISSUE TITLE
Collection ListView preferences not preserved, (collection).admin.defaultColumns doesn't work

### ISSUE THREAD

**Issue by HarleySalas** [payloadcms/payload-3.0-alpha-demo#18]
If you reorder columns in any Collection table (aka `ListView`) and refresh the page, or leave and come back, the order is not persisted.

Also, if you set `defaultColumns` in a collection's `admin.defaultColumns`, it also does not work. I even wiped my database to ensure those defaultColumns are never loaded in.

Should be fairly straight forward to reproduce; I'm using postgres if it matters and all alpha version are on `alpha.41`, with pnpm, using the latest `payload-3.0-alpha-demo` repo.

**Comment by JarrodMFlesch** [comment]
Related: https://github.com/payloadcms/payload-3.0-alpha-demo/issues/29

**Comment by HarleySalas** [comment]
> Related: https://github.com/payloadcms/payload-3.0-alpha-demo/issues/29

Sorry, I forgot about this one 😅 was tired and opened a lot of issues

**Comment by jacobsfletch** [comment]
Yes @HarleySalas the first part of this issue is duplicative (the list preferences stuff) although the second part about default columns is new. BUT I just test this and `defaultColumns` _is_ working as expected. When no `payload_preferences` set for the user, these are used instead.  It could be that this issue was already solved by unrelated changes to caching and/or HMR. Could you try again after we get another alpha out? If the issue persists, feel free to provide some clear steps to reproduction. Closing until then. Thank you for reporting on this 👍
