### ISSUE TITLE
Collection.auth.strategies not working properly

### ISSUE THREAD

**Issue by HarleySalas** [payloadcms/payload-3.0-alpha-demo#44]
I switched my user collection from this:

```
export const User: CollectionConfig = {
  slug: "user",
  auth: true,
  ```

to this:
```
export const User: CollectionConfig = {
  slug: "user",
  auth: {
    strategies: [
      {
        name: "discord",
        authenticate: discordAuthenticationStrategy,
      },
    ],
  },
  ```

Now, when I logout, it says I've successfully logged out. If I press `Log back in`, it just instantly brings me to the `/admin` page, without any authentication whatsoever. It also just sets me as the most recently created user, or a random user.

currently discordAuthenticationStrategy just returns `null`.

aside from this; a full OAuth example would be really nice.

**Edit;**
I swear I restarted my dev server to verify that it was broken and it was still broken. After restarting again, it does seem to still use the local strategy... However, I have a `console.log` running in the `discordAuthenticationStrategy` and it fires **a lot**. This is the phase that we'd be requesting access + refresh tokens and api data directly from the OAuth provider, correct? So, this should definitely only be firing on logins and potentially token refreshes?

Not to mention... I was also using the local strategy to login. `discordAuthenticationStrategy` should not even fire once.

**Comment by jmikrut** [comment]
Hey @HarleySalas — so, authentication runs _**on every request to a Payload API**_. This is how it is in 2.0 as well.

Any custom auth strategies run _**before**_ the built-in local auth strategy, but if they all return null, the built-in auth strategy will still execute.

So it's up to your custom auth strategy to be as performant as possible. You may indeed have to go out and fetch a user from a third-party source, but you might want to hit your OAuth provider and then store the result in an HTTP-only cookie only on login / refresh, as you mentioned, and then for the regular authenticate function, you would simply look at that cookie rather than continuing to hit your third-party.

But that part's up to you and what you want to do. Does that make sense? We do plan on going through how all of this works a little further in a video coming out soon, so keep an eye out for that. But as for now, I believe this is all working as intended. If there is a discrepancy that you can find, please do feel free to let me know and I will re-open this issue!

**Comment by jmikrut** [comment]
Oh also I forgot to mention - 

> Now, when I logout, it says I've successfully logged out. If I press Log back in, it just instantly brings me to the /admin page, without any authentication whatsoever. It also just sets me as the most recently created user, or a random user.

Are you doing anything custom in your logout operation? We can't replicate this, but if you could provide some steps to reproduce, we'll re-open for this part of your issue as well and tackle accordingly.

Thank you!
