### ISSUE TITLE
CLI crashes when resolving CommonJS node_modules & Next.js externals

### ISSUE THREAD

**Issue by sannajammeh** [payloadcms/payload-3.0-alpha-demo#45]
The CLI incorrectly resolves dependencies and crashes with "module not found" error. 

This makes it impossible to build custom components for Payload using Next.js components like `next/link` and having type generation working. Next.js does not use `exports` in package.json for its modules, making module discovery in ESM impossible. 

![image](https://github.com/payloadcms/payload-3.0-alpha-demo/assets/50969683/88094449-3984-445c-a86c-1422f226aff3)

**Comment by jmikrut** [comment]
Hey there - thank you for the report! We'll address this immediately!

**Comment by twosixstudio** [comment]
Upgrading to next@14.2.0-canary.25 seems to fix this.

**Comment by jmikrut** [comment]
Hey all, this issue is related:

https://github.com/payloadcms/payload-3.0-alpha-demo/issues/50

And I've written up a good amount of detail, describing our fix. The fix will be released in the next alpha which is publishing as I write this. If you still experience issues, let us know on #50 and we will re-open accordingly!
